# Generated by Django 3.0.5 on 2020-05-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperName', models.CharField(max_length=100)),
                ('paperDescription', models.CharField(max_length=10000)),
                ('paper', models.FileField(upload_to='research_papers/')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperName', models.CharField(max_length=100)),
                ('paperDescription', models.CharField(max_length=10000)),
                ('paper', models.FileField(upload_to='research_papers/')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
