# Generated by Django 3.0.5 on 2020-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='date',
            field=models.DateField(),
        ),
    ]
