# Generated by Django 3.0.5 on 2020-05-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalsite', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(max_length=2587),
        ),
        migrations.AlterField(
            model_name='research',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
